import type { Chain } from '@wormhole-foundation/sdk-connect';

export const EVMs: Chain[] = [
  'Ethereum',
  'Sepolia',
  'Avalanche',
  'Acala',
  'Arbitrum',
  'ArbitrumSepolia',
  'Aurora',
  'Base',
  'BaseSepolia',
  'Berachain',
  'Blast',
  'Bsc',
  'Celo',
  'Fantom',
  'Gnosis',
  'Karura',
  'Klaytn',
  'Holesky',
  'Linea',
  'Mantle',
  'Moonbeam',
  'Neon',
  'Oasis',
  'Optimism',
  'OptimismSepolia',
  'Polygon',
  'PolygonSepolia',
  'Rootstock',
  'Seievm',
  'Scroll',
  'Xlayer',
];
